name: MLOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # Deploy job will be skipped for PRs due to its 'if' condition
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DVC and Pull Data from GCS
        run: |
          echo "Authenticating to Google Cloud..."
          echo '${{ secrets.GCP_SA_KEY }}' > gcp_creds_ci.json
          export GOOGLE_APPLICATION_CREDENTIALS=./gcp_creds_ci.json
          echo "DVC setup: Using GCS remote."
          echo "Pulling DVC tracked data from GCS..."
          dvc pull data/raw/reviews.csv -v
          echo "DVC data pull attempt finished."
          ls -lh data/raw/
          rm -f gcp_creds_ci.json

      - name: Reproduce DVC pipeline
        run: |
          echo "Attempting to reproduce DVC pipeline..."
          dvc repro -v
          echo "DVC pipeline reproduction attempt finished."
          echo "Listing models directory after DVC repro:"
          ls -lh models/

      - name: Lint with Flake8
        run: |
          echo "Running Flake8 linter on src/ directory..."
          flake8 src/

      - name: Run Tests with Pytest
        run: |
          echo "Running Pytest..."
          pytest tests/ -v

  build_docker_and_push_to_gcr: # Renamed job for clarity
    name: Build and Push Docker Image to GCR
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (for DVC, GCR Push, and GCloud CLI)
        id: auth # Give auth step an ID
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Python for Docker Build Job
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up DVC and Pull Models for Docker Build
        env:
          # GOOGLE_APPLICATION_CREDENTIALS is set by the auth action for gcloud,
          # but DVC Python library might need it explicitly for this run script.
          # However, the auth action also configures gcloud, which DVC might use.
          # For direct DVC use within this script, we re-export it from the temp file.
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_creds_for_dvc.json
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp_creds_for_dvc.json # Create separate for DVC if needed
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          echo "Finished installing dependencies from requirements.txt."
          
          python -c "import dvc_gs; print('dvc_gs imported successfully!')" || (pip list && exit 1)

          echo "Pulling models for Docker build..."
          mkdir -p models 
          dvc pull models/sentiment_model.joblib models/tfidf_vectorizer.joblib -v
          echo "Models pulled."
          ls -lh models/
          rm -f gcp_creds_for_dvc.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use Google Cloud CLI credential helper for GCR
        # This uses the gcloud CLI (already authenticated by the 'auth' step)
        # to configure Docker to be able to push to gcr.io for the authenticated project.
        run: gcloud auth configure-docker gcr.io --quiet 
             # You can add other GCR hostnames if needed, e.g., us.gcr.io, eu.gcr.io
             # Or specific Artifact Registry hostnames like '${{ secrets.CLOUD_RUN_REGION }}-docker.pkg.dev'

      - name: Get current date
        id: date
        run: echo "DATE=$(date --iso-8601=seconds)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to GCR
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true # Actually push the image
          tags: | # Tags for GCR
            gcr.io/${{ steps.auth.outputs.project_id }}/sentiment-analysis-mlops:latest
            gcr.io/${{ steps.auth.outputs.project_id }}/sentiment-analysis-mlops:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.date.outputs.DATE }}

      - name: Image Digest
        run: |
          echo "Pushed image with digest: ${{ steps.docker_build.outputs.digest }}"

  deploy_to_cloud_run:
    name: Deploy to Google Cloud Run
    needs: build_docker_and_push_to_gcr # Depends on the GCR push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Authenticate to Google Cloud
        id: auth 
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Google Cloud Run
        id: deploy_cloud_run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE_NAME || 'sentiment-analysis-api' }} 
          region: ${{ secrets.CLOUD_RUN_REGION || 'europe-west1' }}     
          project_id: ${{ steps.auth.outputs.project_id }} 
          # Image now comes from GCR
          image: gcr.io/${{ steps.auth.outputs.project_id }}/sentiment-analysis-mlops:${{ github.sha }}
          flags: '--allow-unauthenticated --port=5001'

      - name: Print Cloud Run Service URL
        if: steps.deploy_cloud_run.outputs.url 
        run: |
          echo "Service deployed to: ${{ steps.deploy_cloud_run.outputs.url }}"

# Ensure a final newline character below this line