name: MLOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DVC and Pull Data from GCS
        run: |
          echo "Authenticating to Google Cloud..."
          echo '${{ secrets.GCP_SA_KEY }}' > gcp_creds_ci.json
          export GOOGLE_APPLICATION_CREDENTIALS=./gcp_creds_ci.json
          echo "DVC setup: Using GCS remote."
          echo "Pulling DVC tracked data from GCS..."
          dvc pull data/raw/reviews.csv -v
          echo "DVC data pull attempt finished."
          ls -lh data/raw/
          rm -f gcp_creds_ci.json

      - name: Reproduce DVC pipeline
        run: |
          echo "Attempting to reproduce DVC pipeline..."
          dvc repro -v
          echo "DVC pipeline reproduction attempt finished."
          echo "Listing models directory after DVC repro:"
          ls -lh models/

      - name: Lint with Flake8
        run: |
          echo "Running Flake8 linter on src/ directory..."
          flake8 src/

      - name: Run Tests with Pytest
        run: |
          echo "Running Pytest..."
          pytest tests/ -v

  build_docker:
    name: Build and Push Docker Image
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python for Docker Build Job
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up DVC and Pull Models for Docker Build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          echo "Finished installing dependencies from requirements.txt."
          
          python -c "import dvc_gs; print('dvc_gs imported successfully! Version:', getattr(dvc_gs, '__version__', 'unknown'))" || \
            (echo "Failed to import dvc_gs. Listing installed packages:" && pip list && exit 1)

          echo "Authenticating to Google Cloud for Docker build..."
          echo '${{ secrets.GCP_SA_KEY }}' > gcp_creds_ci.json
          export GOOGLE_APPLICATION_CREDENTIALS=./gcp_creds_ci.json
          
          echo "--- Running dvc version ---"
          dvc version

          echo "--- Running dvc doctor ---"
          dvc doctor || echo "dvc doctor reported issues but proceeding..."
          
          echo "Ensuring models directory exists for DVC operations..."
          mkdir -p models

          echo "--- Checking status of remote 'mygcsremote' for specific model files (using --json) ---"
          dvc status -r mygcsremote models/sentiment_model.joblib models/tfidf_vectorizer.joblib -v --json || \
            echo "dvc status -r mygcsremote --json failed or showed unexpected status. Output above."

          echo "--- Attempting dvc fetch for specific model files ---"
          dvc fetch models/sentiment_model.joblib models/tfidf_vectorizer.joblib -v
          echo "--- dvc fetch command completed ---"
          
          echo "--- Listing DVC cache contents after fetch ---"
          echo "Checking for general cache structure:"
          ls -la .dvc/cache/files/md5/ || echo "MD5 cache directory does not exist or is empty."
          echo "Number of files in DVC cache:"
          find .dvc/cache -type f -print0 | xargs -0 --no-run-if-empty wc -l || echo "Could not count files in DVC cache or cache is empty."
          echo "Listing some files in DVC cache (if any):"
          find .dvc/cache -type f -print0 | xargs -0 --no-run-if-empty ls -l | head -n 10 || echo "DVC cache is empty or find command failed."

          echo "--- Attempting dvc checkout for specific model files ---"
          dvc checkout models/sentiment_model.joblib models/tfidf_vectorizer.joblib -v
          echo "--- dvc checkout command completed ---"

          echo "Models pull process finished. Listing models directory:"
          ls -lh models/
          if [ -s models/sentiment_model.joblib ] && [ -s models/tfidf_vectorizer.joblib ]; then
            echo "Model files successfully checked out and are not empty."
          else
            echo "ERROR: Model files were not checked out correctly or are empty."
            # exit 1 # Keep commented out for now to see all logs from this job
          fi
          
          rm -f gcp_creds_ci.json

      - name: Debug GitHub Context Variables # NEW DEBUGGING STEP
        run: |
          echo "github.repository: ${{ github.repository }}"
          echo "github.repository_lower: ${{ github.repository_lower }}"
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.repository_owner_lower: ${{ github.repository_owner_lower }}"
          echo "github.event.repository.name: ${{ github.event.repository.name }}"
          echo "github.event.repository.name_lower: ${{ github.event.repository.name_lower }}" # Corrected from just name_lower
          echo "github.actor: ${{ github.actor }}"
          echo "github.actor_lower: ${{ github.actor_lower }}" # Added for completeness

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "DATE=$(date --iso-8601=seconds)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to GHCR
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor_lower }}/sentiment-analysis-mlops:latest
            ghcr.io/${{ github.actor_lower }}/sentiment-analysis-mlops:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.date.outputs.DATE }}

      - name: Image Digest
        run: |
          echo "Pushed image with digest: ${{ steps.docker_build.outputs.digest }}"

# Ensure a final newline character below this line